// FIX: This file was empty. It has been populated with the necessary content to resolve module import errors.
export const en = {
  header: {
    title: "Taiwan Clay",
    shop: "All Products",
    about: "About",
    training: "Teacher Training",
    english: "English",
    traditionalChinese: "繁體中文",
    simplifiedChinese: "简体中文",
  },
  shop: {
    categoryTitle: "Categories",
    allProducts: "All Products",
    backToProducts: "Back to Products",
  },
  product: {
    selectColor: "Select Color",
    addToCart: "Add to Cart",
    searchPlaceholder: "Search for products...",
    noResults: "No products found matching your search.",
    quantity: "Quantity",
  },
  cart: {
    title: "Your Cart",
    empty: "Your cart is empty.",
    remove: "Remove",
    total: "Total",
    clear: "Clear Cart",
    checkout: "Checkout",
  },
  about: {
    title: "Why Choose Taiwan Clay?",
    imageAlt: "Vibrant polymer clay color chart",
    feature1Title: "Safe and Non-toxic",
    feature1Text: "Locally produced in Taiwan, our polymer clay is certified by national safety inspections, so you can use it with peace of mind.",
    feature2Title: "Highly Malleable",
    feature2Text: "Polymer clay has high ductility and plasticity, with excellent adhesion, allowing you to work without it sticking to your hands.",
    feature3Title: "Permanent Shaping",
    feature3Text: "Polymer clay is a thermoplastic material. It can be hardened by baking in a regular home oven at a low temperature (130°C) for 10-15 minutes.",
    story: {
      title: "Our Polymer Clay Story",
      subtitle: "Starting with a piece of clay, inheriting a father's craft.",
      card1Title: "Keeping a Father's Craft Shining",
      card1ContentP1: "As a child, my father would always sit in a corner of the factory, diligently crafting unique Taiwanese polymer clay art. It was the business he was most proud of. And we grew up in that space, filled with the warm aroma of the oven.",
      card1ContentP2: "Back then, I didn't quite understand why this clay was so special. It wasn't until I placed it in the oven with my own hands, watching its soft form slowly solidify, becoming preserved like a memory, that I understood—this was a kind of magic that could make creativity last forever.",
      card1ContentP3: "Our polymer clay is a high-quality polymer material (Polymer Clay), a type of thermoplastic. Simply use a household electric oven at 130°C for 10-15 minutes to complete your own work. The creative process itself is the most moving story.",
      card2Title: "A Material Born for Creation",
      card2Item1: "High ductility and plasticity: Shape detailed, glossy, and richly colored forms.",
      card2Item2: "Safe, non-toxic, and easy to handle: Oil-based, non-irritating, and non-sticky, making creation feel free.",
      card2Item3: "Durable and shape-retaining: Waterproof, mold-proof, and pest-resistant for long-lasting creations.",
      card2Item4: "Freely mixable colors: Blend colors to create your own unique shades.",
      card2Item5: "Multi-material compatibility: Combine with heat-resistant materials like metal, wood, and glass.",
      card3Title: "For Everyone Who Wants to Create",
      card3ContentP1: "Whether you're a first-timer or an old friend seeking inspiration through crafting, polymer clay can be a medium to express your emotions and imagination.",
      card3ContentP2: "Here, every pair of hands can create its own world.",
      card3ContentP3: "Let a soft piece of polymer clay be the beginning of your story.",
    }
  },
  training: {
    title1: "Polymer Clay Instructor Training",
    courseType: "Course Type:",
    courseTypeA: "A. Department Store Polymer Clay Counter Staff Training",
    courseTypeB: "B. Polymer Clay Creation Training",
    duration: "Training Duration: 24 hours.",
    location: "Location: 8F-5, No. 16, Section 1, Chang'an East Road, Taipei City.",
    fee: "Fee: Starting from NT$35,000 (includes polymer clay materials, tools, accessories, and a desktop pasta machine).",
    classSize: "Class Size: Counter staff group (2-3 people).",
    targetAudience: "Target Audience:",
    targetAudienceA: "A. Individuals wishing to work at a department store polymer clay counter.",
    targetAudienceB: "B. Individuals looking to learn a second skill and for employment.",
    title2: "Course Content:",
    content1: "1. Polymer clay characteristics.",
    content2: "2. Color mixing techniques for polymer clay.",
    content3: "3. Polymer clay jewelry creation.",
    content4: "4. Polymer clay cane and millefiori techniques.",
    content5: "5. Creation of fashion accessories.",
  },
  footer: {
      contactUs: {
        line: "Contact Us",
        companyName: "Taiwan Clay Co., Ltd.",
        phone: "Phone",
        taxId: "Company ID",
        ctaTitle: "Have a Question?",
        ctaText: "Whether you have questions about our courses, need material suggestions, or have an order inquiry, we're here to help. Feel free to reach out!"
      },
      copyright: "Copyright 1997-2025 © 台灣軟陶有限公司 Taiwan Clay",
  }
};