// FIX: This file was empty. It has been populated with the necessary content to resolve module import errors.
export const zhCN = {
  header: {
    title: "台湾软陶",
    shop: "所有商品",
    about: "关于我们",
    training: "师资培训",
    english: "English",
    traditionalChinese: "繁體中文",
    simplifiedChinese: "简体中文",
  },
  shop: {
    categoryTitle: "商品分类",
    allProducts: "所有商品",
    backToProducts: "返回商品列表",
  },
  product: {
    selectColor: "选择颜色",
    addToCart: "加入购物车",
    searchPlaceholder: "搜寻商品...",
    noResults: "找不到符合您搜寻的商品。",
    quantity: "数量",
  },
  cart: {
    title: "您的购物车",
    empty: "您的购物车是空的。",
    remove: "移除",
    total: "总计",
    clear: "清空购物车",
    checkout: "结帐",
  },
  about: {
    title: "为什么选择台湾软陶？",
    imageAlt: "缤纷的软陶色票",
    feature1Title: "安全无毒",
    feature1Text: "台湾在地生产，我们的软陶经过国家安全检验认可，让您用得安心。",
    feature2Title: "可塑性高",
    feature2Text: "软陶具高度延展性、可塑性，本身有绝佳的黏性，让您操作起来完全不黏手。",
    feature3Title: "可永久定型",
    feature3Text: "软陶属于热塑性材料，用一般家庭烤箱（130°C）低温烘烤10～15分钟，即可硬化。",
    story: {
      title: "我们的软陶故事",
      subtitle: "从一块软陶开始，传承父亲的工艺",
      card1Title: "让父亲的工艺继续发光",
      card1ContentP1: "小时候，父亲总是坐在工厂的一角，辛勤的制作着属于台湾的独特软陶工艺，那是他最引以为傲的事业。而我们，从小就在那个有着温暖烤箱香气的空间里长大。",
      card1ContentP2: "那时候的我，还不太懂这些土为什么这么特别。直到亲手把它放进烤箱，看着柔软的形体在烤箱中慢慢变得结实、变得像记忆一样被封存。我才明白——这是一种能让创意永恒存在的魔法。",
      card1ContentP3: "我们的软陶是高品质聚合性材料（PolymerClay），属于热塑性材质。只要用家用电烤箱，以 130°C 烘烤 10～15分钟，就能完成属于你自己的作品，创作的过程本身，就是最动人的故事。",
      card2Title: "为创作而生的材质",
      card2Item1: "超高延展性与可塑性：能塑造出细致、有光泽、色彩饱满的造型。",
      card2Item2: "安全无毒，亲肤好操作：油性成分不刺激、不沾手，让创作更自在。",
      card2Item3: "耐久保存不变形：防水、防霉、不怕虫蛀，作品能长久留存。",
      card2Item4: "自由调色：混合色彩，创造只属于你的独特色调。",
      card2Item5: "多材质结合：可与金属、木头、玻璃等耐温材质搭配创作。",
      card3Title: "给每一位想动手创造的人",
      card3ContentP1: "无论你是第一次接触手作，还是早已在创作中寻找灵感的老朋友，软陶都能成为你表达情感与想像的媒介。",
      card3ContentP2: "在这里，每一双手都能创造出自己的世界。",
      card3ContentP3: "让一块柔软的软陶土，成为你故事的开端。",
    }
  },
  training: {
    title1: "软陶师资特训",
    courseType: "班别：",
    courseTypeA: "A. 百货公司软陶专柜人员培训班",
    courseTypeB: "B. 软陶创作培训。",
    duration: "培训时间：24小时。",
    location: "上课地点：台北市长安东路一段16号8F之5。",
    fee: "费用：35000元 起(含软陶材料、工具、配件、桌上型压面机)。",
    classSize: "名额：同组专柜人员(2-3人)。",
    targetAudience: "对象：",
    targetAudienceA: "A. 欲从事百货公司软陶专柜人员",
    targetAudienceB: "B. 想学习第二专长及就业者。",
    title2: "课程内容：",
    content1: "1. 软陶特性。",
    content2: "2. 软陶配色技巧。",
    content3: "3. 软陶饰品创作。",
    content4: "4. 软陶花条拼图技巧。",
    content5: "5. 流行饰品之创作。",
  },
  footer: {
    contactUs: {
        line: "联系我们",
        companyName: "台湾软陶有限公司",
        phone: "电话",
        taxId: "统编",
        ctaTitle: "有任何问题吗？",
        ctaText: "无论是课程询问、材料建议或订单问题，都欢迎随时与我们联系！我们很乐意为您服务。"
      },
    copyright: "Copyright 1997-2025 © 台灣軟陶有限公司 Taiwan Clay",
  }
};