// FIX: This file was empty. It has been populated with the necessary content to resolve module import errors.
export const zhTW = {
  header: {
    title: "台灣軟陶",
    shop: "所有商品",
    about: "關於我們",
    training: "師資培訓",
    english: "English",
    traditionalChinese: "繁體中文",
    simplifiedChinese: "简体中文",
  },
  shop: {
    categoryTitle: "商品分類",
    allProducts: "所有商品",
    backToProducts: "返回商品列表",
  },
  product: {
    selectColor: "選擇顏色",
    addToCart: "加入購物車",
    searchPlaceholder: "搜尋商品...",
    noResults: "找不到符合您搜尋的商品。",
    quantity: "數量",
  },
  cart: {
    title: "您的購物車",
    empty: "您的購物車是空的。",
    remove: "移除",
    total: "總計",
    clear: "清空購物車",
    checkout: "結帳",
  },
  about: {
    title: "為什麼選擇台灣軟陶？",
    imageAlt: "繽紛的軟陶色票",
    feature1Title: "安全無毒",
    feature1Text: "台灣在地生產，我們的軟陶經過國家安全檢驗認可，讓您用得安心。",
    feature2Title: "可塑性高",
    feature2Text: "軟陶具高度延展性、可塑性，本身有絕佳的黏性，讓您操作起來完全不黏手。",
    feature3Title: "可永久定型",
    feature3Text: "軟陶屬於熱塑性材料，用一般家庭烤箱（130°C）低溫烘烤10～15分鐘，即可硬化。",
    story: {
      title: "我們的軟陶故事",
      subtitle: "從一塊軟陶開始，傳承父親的工藝",
      card1Title: "讓父親的工藝繼續發光",
      card1ContentP1: "小時候，父親總是坐在工廠的一角，辛勤的製作著屬於台灣的獨特軟陶工藝，那是他最引以為傲的事業。而我們，從小就在那個有著溫暖烤箱香氣的空間裡長大。",
      card1ContentP2: "那時候的我，還不太懂這些土為什麼這麼特別。直到親手把它放進烤箱，看著柔軟的形體在烤箱中慢慢變得結實、變得像記憶一樣被封存。我才明白——這是一種能讓創意永恆存在的魔法。",
      card1ContentP3: "我們的軟陶是高品質聚合性材料（PolymerClay），屬於熱塑性材質。只要用家用電烤箱，以 130°C 烘烤 10～15分鐘，就能完成屬於你自己的作品，創作的過程本身，就是最動人的故事。",
      card2Title: "為創作而生的材質",
      card2Item1: "超高延展性與可塑性：能塑造出細緻、有光澤、色彩飽滿的造型。",
      card2Item2: "安全無毒，親膚好操作：油性成分不刺激、不沾手，讓創作更自在。",
      card2Item3: "耐久保存不變形：防水、防霉、不怕蟲蛀，作品能長久留存。",
      card2Item4: "自由調色：混合色彩，創造只屬於你的獨特色調。",
      card2Item5: "多材質結合：可與金屬、木頭、玻璃等耐溫材質搭配創作。",
      card3Title: "給每一位想動手創造的人",
      card3ContentP1: "無論你是第一次接觸手作，還是早已在創作中尋找靈感的老朋友，軟陶都能成為你表達情感與想像的媒介。",
      card3ContentP2: "在這裡，每一雙手都能創造出自己的世界。",
      card3ContentP3: "讓一塊柔軟的軟陶土，成為你故事的開端。",
    }
  },
  training: {
    title1: "軟陶師資特訓",
    courseType: "班別：",
    courseTypeA: "A. 百貨公司軟陶專櫃人員培訓班",
    courseTypeB: "B. 軟陶創作培訓。",
    duration: "培訓時間：24小時。",
    location: "上課地點：台北市長安東路一段16號8F之5。",
    fee: "費用：35000元 起(含軟陶材料、工具、配件、桌上型壓麵機)。",
    classSize: "名額：同組專櫃人員(2-3人)。",
    targetAudience: "對象：",
    targetAudienceA: "A. 欲從事百貨公司軟陶專櫃人員",
    targetAudienceB: "B. 想學習第二專長及就業者。",
    title2: "課程內容：",
    content1: "1. 軟陶特性。",
    content2: "2. 軟陶配色技巧。",
    content3: "3. 軟陶飾品創作。",
    content4: "4. 軟陶花條拼圖技巧。",
    content5: "5. 流行飾品之創作。",
  },
  footer: {
      contactUs: {
        line: "聯絡我們",
        companyName: "台灣軟陶有限公司",
        phone: "電話",
        taxId: "統編",
        ctaTitle: "有任何問題嗎？",
        ctaText: "無論是課程詢問、材料建議或訂單問題，都歡迎隨時與我們聯繫！我們很樂意為您服務。"
      },
      copyright: "Copyright 1997-2025 © 台灣軟陶有限公司 Taiwan Clay",
  }
};